all:
  hosts:
  children:
    aws_first_server:
      hosts:
        first_server:
          ansible_host: 46.137.63.26
    aws_second_server:
      hosts:
        second_server:
          ansible_host: 54.72.216.136
    aws_common_group:
      children:
        aws_first_server:
        aws_second_server: