version: "3.9"

services:
  web:
    container_name: flask
    hostname: flask
    build: .
    image: weather
    environment:
      API_KEY: ${API_KEY}
      NAME: ${NAME}
      CITY: ${CITY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5000:5000"
    networks:
      - db_network
    restart: always
    depends_on:
      - db


  db:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db_network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 45s
      interval: 60s
      retries: 10
    restart: always    


networks:
  db_network:
    driver: bridge