FROM python:3.7-alpine

LABEL mantainer="gootsev@gmail.com"

ENV API_KEY="none"
ENV NAME="none"
ENV CITY="none"

WORKDIR /app/
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY ./app.py /app/

EXPOSE 5000
ENTRYPOINT ["python3", "/app/app.py"]