---
- name: enable service on boot
  service:
    name: "amazon-cloudwatch-agent"
    enabled: "yes"

- name: restart amazon-cloudwatch-agent
  service:
    name: "amazon-cloudwatch-agent"
    state: "restarted"